### ISSUE TITLE
Native advanced ads support

### ISSUE THREAD

**Issue by nameer94** [MatheusAlvesA/react-native-androide#2] opened 2019-07-23 14:46 UTC
Finally a good package for admob
but somehow it didn't work unless I add this code to `android/app/build.gradle`
```
configurations.all {
resolutionStrategy {
force "com.google.android.gms:play-services-base:16.1.0"
force "com.google.android.gms:play-services-gcm:16.1.0"
force "com.google.android.gms:play-services-ads:17.2.0" } }

dependencies {
    ...
    implementation ('com.google.android.gms:play-services-ads:18.0.0'){ force = true; } 
}
```
according to this issue https://github.com/sbugert/react-native-admob/issues/452

Can you add support for admob Native advanced ads?
Thank you :)

**Comment by MatheusAlvesA** [comment] 2019-07-24 01:47
Hey, thanks for this first issue.

This issue is caused by a incompatibility of the Java Code in libs that use old Support Libraries of Android and the new Androidx libraries used by admob core code.

**To solve that:**
Delete all this code that you put in you `android/app/build.gradle` file. This lines force de use of old libraries and this can cause bugs.

Force the use of the new Androidx code in your react-native project. To do this, you will only need to put  this lines:

```
android.enableJetifier=true
android.useAndroidX=true
```

in your `android/gradle.properties` file.

Then try to build and tell me if works.

### Long Explanation

react-native was builded for Android with the [Android Support Library](https://developer.android.com/topic/libraries/support-library), but this libs will be replaced by Google to [Androidx Library](https://developer.android.com/jetpack/androidx). So the react-native team [starts to migrate](https://github.com/facebook/react-native/releases/tag/v0.60.0) to the new Androidx libs. Since the version 0.60.0 of react-native the Androidx is enabled by default.  
Unfortunately before this version Androidx wasn't used and libs that uses Androidx(like AdMob) causes conflicts with the old libs used by react-native(<0.60.0).

[Jetifier](https://github.com/jumpn/react-native-jetifier) is a tool used by react-native to convert automatically code to the new Androidx lib, therefore turning the project compatible with the new Google's Lib and solving the bug with the AdMob.

**Comment by MatheusAlvesA** [comment] 2019-07-24 01:50
About the Native advanced Ads.

I want to implement this but can't say when it will be released.

**Comment by nameer94** [comment] 2019-07-24 09:37
It works, thanks

**Closed as completed** 2019-07-24 23:24 UTC
